### ISSUE TITLE
compiling to .exe

### ISSUE THREAD

**Issue by kekec14** [drunsinn/pyLSV2#20]
Hello!

When I try to compile my script to .exe with py2exe, translations are not included. Any idea how to achieve to include translations (/locales folder). 

problematic functions are:
`get_program_status_text()` and `get_execution_status_text()`.

Thank you!

**Comment by drunsinn** [comment]
I was able to confirm your steps, manually adding the translation files makes it work but I can't figure out what I could change in pyLSV2 to make py2exe include the mo files. The packages include the translation files so I would think pyLSV2's setup.py works as intended.

Going forward I can remove the translation stuff entirely and hardcode the messages. As I don't see myself adding additional languages this might be the easiest solution to this problem.

**Comment by drunsinn** [comment]
Ok, I did some more digging. It seems to be a problem with py2exe only checking for *.py files and nothing else. A work around is to manually add files but this does not allow adding files to library.zip.
I created #21 which lets you set the path for the translation files manually. This together with adding the files seems to work great!
To test I used this setup.py script:

```
from distutils.core import setup
import glob
import pyLSV2

baseFolder = pyLSV2.__file__.strip('_init_.py')
mylocaleEN = glob.glob(baseFolder+"\\locales\\en\\LC_MESSAGES\\*.mo")
mylocaleDE = glob.glob(baseFolder+"\\locales\\de\\LC_MESSAGES\\*.mo")

data_files = [("locale\\en\\LC_MESSAGES", mylocaleEN),
               ("locale\\de\\LC_MESSAGES", mylocaleDE)]

setup(console=['lsv2_demo.py'], data_files=data_files)
```

together with this test script:
```
import pyLSV2

locale_folder = "./locale"

print(pyLSV2.__version__, pyLSV2.__file__)
print(pyLSV2.get_program_status_text(pyLSV2.PgmState.STOPPED, locale_path=locale_folder))
print(pyLSV2.get_program_status_text(pyLSV2.PgmState.STOPPED, language='de', locale_path=locale_folder))
print(pyLSV2.get_program_status_text(pyLSV2.PgmState.STOPPED, language='en', locale_path=locale_folder))
```

I hope #21 and changing the setup.py works for you!
