### ISSUE TITLE
Can I start or stop a specify program by pyLSV2?

### ISSUE THREAD

**Issue by pangafu** [drunsinn/pyLSV2#33]
I can read program status by con.get_program_status().
Can I stop/start a specify program ?

**Comment by drunsinn** [comment]
not as far as I know. maybe via dnc but not with only lsv2

**Comment by drunsinn** [comment]
@pangafu after reviewing some documents the only thing I could find was something called drip feeding but this still requires the user to press the start button on the control. This is probably a safety feature.

**Comment by pangafu** [comment]
@drunsinn 
Thansk a lot~
