### ISSUE TITLE
Cann't connect to the Haidenhain system (version TNC640)

### ISSUE THREAD

**Issue by NecoMai** [drunsinn/pyLSV2#36]
Hi drunsinn

      I think there maybe something wrong in the program, or something configuration in the machine had been modified.

     One controller infomation of grob machine can be read from the program:
     Controller Information:
     TNC-Type:	TNC640
     NC-Version:	340590 10 SP2
     PLC-Version:	TNC640_V14.06.05

    But the other controller infomation of HERMLE machine(C42U) can not be read suddenly。

    This is an earlier result：
    E:\pyLSV2-master\venv\Scripts\python.exe E:/pyLSV2-master/JCTest.py
    Connecting to 192.168.1.37
    {'Control': 'TNC640', 'NC_Version': '340590 10 SP3', 'PLC_Version': 'C42.33.04SP2HF1/S/'}

Connecting to 192.168.1.37
ERROR:root:something went wrong while waiting for new data to arrive, buffer was set to 256
Traceback (most recent call last):
  File "E:/pyLSV2-master/JCTest.py", line 12, in <module>
    con.connect()
  File "E:\pyLSV2-master\pyLSV2\client.py", line 94, in connect
    self._configure_connection()
  File "E:\pyLSV2-master\pyLSV2\client.py", line 229, in _configure_connection
    self.login(login=Login.INSPECT)
  File "E:\pyLSV2-master\pyLSV2\client.py", line 323, in login
    if not self._send_recive_ack(CMD.A_LG, payload):
  File "E:\pyLSV2-master\pyLSV2\client.py", line 206, in _send_recive_ack
    response, content = self._llcom.telegram(
  File "E:\pyLSV2-master\pyLSV2\low_level_com.py", line 122, in telegram
    response = self._tcpsock.recv(buffer_size)
socket.timeout: timed out

**Comment by drunsinn** [comment]
Did you manage to fix it yourself?
Looks to me like the control didn't respond. Let me guess, you had to enable the connection on the control?
Been there myself ;-)
