### ISSUE TITLE
signals at long & short intervals together

### ISSUE THREAD

**Issue by Md-aliy7** [drunsinn/pyLSV2#46]
Hi,

I noticed that TNCscope can read signals of long intervals (e.g., position and velocity: 3 ms) & signals of short intervals (e.g., current: 0.6 ms) together with considering the frequency of each one (like position is updated only one time when the current can be updated 5 times at interval = 600 us chosen for both of them. As shown in the attached picture (current & velocity at x-axis):
![image](https://user-images.githubusercontent.com/119819019/230775905-10eeafe8-b224-4324-9603-028087abde66.png)

I could change the code to behave like as following:

1- Cancelling these two lines:
![image](https://user-images.githubusercontent.com/119819019/230775986-73dcfef3-7071-4854-aaad-09ffaa6c1780.png)

2- Cancelling these lines:
![image](https://user-images.githubusercontent.com/119819019/230776037-29877bd9-5ee8-4c99-a608-61fe887dd2c5.png)

3- Adding this if condition (special for interval = 600 us):
![image](https://user-images.githubusercontent.com/119819019/230776602-6bbc7c2f-4f78-4509-bb43-dd04794199bc.png)

while this (count_high_freq) increases by one at the end of each for-inner loop.
It gives the same exact behavior, but this is very specific for interval = 600 us (as mentioned above) because of the very soft code while TNCscope has fewer choices with more codes of conditions.
I wonder if you have a better solution for it.

**Comment by Md-aliy7** [comment]
I suggest modifying the code to be:
![image](https://user-images.githubusercontent.com/119819019/232205702-4b24aeef-8c47-4c0e-8dc1-9a8e740e804c.png)

What do you think?

**Comment by drunsinn** [comment]
@Md-aliy7 sorry for the late reply.
I tried to follow your suggestions but to be honest I am not certain I understand all of it :-)
Nevertheless your changes look good to me, I see no problem to integrate them as they are.

Can you create a pull request? Would be easier for me to integrate.

**Comment by drunsinn** [comment]
Your changes have been integrated and a new release should be available shortly, thanks for the code!
