### ISSUE TITLE
an error occurred while querying system information

### ISSUE THREAD

**Issue by Andreas-strg** [drunsinn/pyLSV2#55]
Hello,

I only use Fletransver for my programming and don't need any DNC or monitor functions, but I still get error messages (iTNC530 and TNC640)
The data transfer then works as desired

Can I deactivate the other logins somehow or what could be the problem?

```
con = pyLSV2.LSV2("172.29.48.126")
con.connect()
con.login(login=pyLSV2.Login.FILETRANSFER)
```
Console:
```
received unexpected response RSP.T_BD
an error occurred while querying system information on turbo mode
received unexpected response RSP.T_BD
an error occurred while querying system information on dnc mode
an error occurred while querying system information on axes samling rate
```
Thanks alot

**Comment by drunsinn** [comment]
These log messages are normal. During the setup phase all known info items are queried to check the capabilities of the control. The queries are handled by the same code as everything else, this is why you see these messages. There is no easy way to get rid of these log messages besides changing the log level of your application to "ERROR".

**Comment by Andreas-strg** [comment]
D
