### ISSUE TITLE
table_reader ERROR:NCTable parser:File has invalid utf-8 encoding

### ISSUE THREAD

**Issue by Andreas-strg** [drunsinn/pyLSV2#59]
Hello,

I have an Error with some .t Tables:
`ERROR:NCTable parser:File has invalid utf-8 encoding`

I think the TNC format encoding is not utf-8

I change in table_reader.py line 302 from
`            with table_file.open(mode="r", encoding="utf-8") as tfp:`
to
`            with table_file.open(mode="r", encoding="ANSi") as tfp:`

and it works again
testet on iTNC530 and TNC640

thanks

**Comment by drunsinn** [comment]
Thank you,I will make add your fix and publish a fixed version shortly!

**Comment by drunsinn** [comment]
fixed in v1.3.3
