### ISSUE TITLE
OUTPUT_DWORD reading PLC memory?

### ISSUE THREAD

**Issue by LanderUrgoiti** [drunsinn/pyLSV2#62]
Hello:

I have been trying to get some values that we write in the PLC memory but I am unable to find them. 
I have loked in the TNC640 control and I can see that calling this function I get the correct values from the DWORD table:

`    AAA = con.read_plc_memory(first_element=27,mem_type=pyLSV2.MemoryType.DWORD, number_of_elements=1)`
`    print(AAA)`

The issue is that I am looking for a DWORD stored in another table ODWORD or something like that. I am guessing this means OUTPUT_DWORD since I can see the OUTPUT_WORD values correctly using this

`    AAA = con.read_plc_memory(first_element=27,mem_type=pyLSV2.MemoryType.OUTPUT_WORD, number_of_elements=1)`
`    print(AAA)`

My question is, Is thete a way to get OUTPUT_DWORD values

![Fig1](https://github.com/drunsinn/pyLSV2/assets/125881152/9729c9f2-22d7-4e07-9439-87a3356f011e)
![Fig2](https://github.com/drunsinn/pyLSV2/assets/125881152/274dec69-8ac4-44a9-8a1a-fd317ce859a5)

**Comment by drunsinn** [comment]
I think I understand what you mean and hope that it is as easy as to add a new data type to the code based on the settings of the regular output words. Currently I can't disturb our machines so it would be grate if you could try out the changes I made in pull request #63 before I merge them.

**Comment by drunsinn** [comment]
@LanderUrgoiti have you been able to confirm if the changes in #63 work?

**Comment by drunsinn** [comment]
support for output d word was added with v1.4
