### ISSUE TITLE
FileTransfer returns ERROR 

### ISSUE THREAD

**Issue by oxbown** [drunsinn/pyLSV2#66]
When I use the send_file I, got `could not send end of transmission telegram, and got the response 'RSP.T_ER'` but the file is sent OK to the controller...
So I found that in the original Eclipse-Plugin, the response for end of transmission is T_ER.

https://github.com/tfischer73/Eclipse-Plugin-Heidenhain/blob/03fb2beec0fb25970f94745700b8f3a8a002af48/Plugin/src/ch/tfischer/hh/client/LSV_Client.java#L65

This line https://github.com/drunsinn/pyLSV2/blob/9dafce0d71d0bd9f8a6eadddde69be77265f3cd4/pyLSV2/client.py#L1073
need to be changed to `if not self._send_recive(lc.RSP.T_FD, None, lc.RSP.T_ER):`

**Comment by drunsinn** [comment]
Ugh, you are correct. This seems to be a copy&past error that happened during some refactoring word.
I will add a new test so this won't happen in the future. Thanks a lot! Expect a new release in one or two days.

**Comment by drunsinn** [comment]
I looked a bit deeper into this, it is correct that there is an error but it isn't the wrong response code. 
Going by protocol documentation i was able to find, without secure file send, no response should be expected from the control. pyLSV2 was missing a check to suppress waiting for a response altogether!
